version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "artisana-order-processor"
        Alias: "live"
        CurrentVersion: "2"
        TargetVersion: "3"