version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install pytest
      - pip install aws-sam-cli

  pre_build:
    commands:
      - pytest tests/

  build:
    commands:
      - echo "build"

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - appspec.yml
    - template.yaml